import sys
from pathlib import Path
script_dir = Path(__file__).parent
import os

########
# Generated by ChatGPT o1-preview, after few interactions it produces
# an actual model, but it seems wrong
#####



# Adjust the path according to where FreeCAD is installed
freecad_path = '/usr/lib/freecad-python3/lib'  # Set your FreeCAD installation path

if freecad_path not in sys.path:
    sys.path.append(freecad_path)
    sys.path.append(script_dir)

print(sys.path)

import FreeCAD
import Part
from FreeCAD import Vector


from tool_shapes import  mill_tool

# Define parameters
radius = 5.0
length = 20.0
direction = Vector(0, 0, 1)  # Tool axis direction
start_point = Vector(0, 0, 0)
end_point = Vector(50, 0, 10)  # Path not perpendicular to the tool axis

# Create the milling tool swept volume
milling_swept_volume = mill_tool(radius, length, direction, start_point, end_point)

# Add the swept volume to the active document for visualization
doc = FreeCAD.ActiveDocument
if doc is None:
    doc = FreeCAD.newDocument()
part_obj = doc.addObject("Part::Feature", "MillingToolSweptVolume")
part_obj.Shape = milling_swept_volume
doc.recompute()
doc.saveAs("mill_tool")